# ===============================
# Application
# ===============================
spring.application.name=gateway              # ← Identifie le service pour le Config Server
spring.config.import=configserver:http://localhost:9999 # ← Dit au service "va chercher ta config ici"
eureka.client.service-url.defaultZone=http://localhost:8761/eureka # ← Pour que le service trouve Eureka
