spring.application.name=config

server.port=9999
spring.cloud.discovery.enabled=true
spring.cloud.config.server.git.uri=https://haroun-ab:glpat-cJGNyVC-1qr0SREVinEyxG86MQp1Omo5ZWk1Cw.01.121i67zwj@gitlab.com/haroun-ab/microservice.git