spring.application.name=config

server.port=9999
spring.cloud.discovery.enabled=true

# Config Server - Fichiers locaux
spring.cloud.config.server.native.search-locations=classpath:/config-files

# Utiliser le profil native pour servir les fichiers locaux
spring.profiles.active=native