spring.application.name=discovery
server.port=8761

# Ne pas enregistrer Eureka Server lui même en tant que client
eureka.client.fetch-registry=false

# Ne pas enregistrer Eureka Server au près du service registry
eureka.client.register-with-eureka=false

# Les services s'enregistrent avec leur IP
eureka.instance.prefer-ip-address=true

# Quand Eureka se trouve sur une autre machine que celle de dev
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Avoid warning message on UI
eureka.server.enableSelfPreservation=true
