# Identifie le service pour le Config Server
spring.application.name=payment
# Dit au service "va chercher ta config ici"
spring.config.import=configserver:http://localhost:9999
# Pour que le service trouve Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
