# Identifie le service pour le Config Server
spring.application.name=user
# Dit au service "va chercher ta config ici"
spring.config.import=configserver:http://config:9999
# Pour que le service trouve Eureka
eureka.client.service-url.defaultZone=http://discovery:8761/eureka
